[font]
size = 14.0

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Bold Italic"
