general.import = [
  "~/.config/alacritty/themes/cyberdream.toml"
]

[font]
size = 14.0

[font.normal]
family = "Agave Nerd Font Mono"
style = "Medium"

[font.bold]
family = "Agave Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Agave Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Agave Nerd Font Mono"
style = "Bold Italic"
